import { useState, useEffect } from "react";
import API from "../API/axois";

const IntQuestion = () => {

  const [project, setProject] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [completed, setCompleted] = useState([]);
  const [search, setSearch] = useState("");

  const projectId = localStorage.getItem("selectedProjectId");

  const fetchInterviewData = async () => {
    try {

      const res = await API.get(`/api/analyzer/project/${projectId}`);

      setProject(res.data.project);
      setAnalysis(res.data.analysis);

    } catch (err) {
      console.log(err);
    }
  };

  useEffect(() => {

    if (projectId) {
      fetchInterviewData();
    }

  }, [projectId]);

  const toggleCompleted = (index) => {

    if (completed.includes(index)) {

      setCompleted(completed.filter(i => i !== index));

    } else {

      setCompleted([...completed, index]);

    }

  };

  const questions = analysis?.interviewQuestions || [];

  const filteredQuestions = questions.filter((q) =>
    q.question.toLowerCase().includes(search.toLowerCase()) // for search
  );

  const easy = questions.filter(q => q.difficulty === "Easy").length;
  const medium = questions.filter(q => q.difficulty === "Medium").length;
  const hard = questions.filter(q => q.difficulty === "Hard").length;

  let overallDifficulty = "Easy";

  if (hard >= medium && hard >= easy) {

    overallDifficulty = "Hard";

  } else if (medium >= easy) {

    overallDifficulty = "Medium";

  }

  return (

    <div className="min-h-screen bg-[#020817] text-white">

      <div className="max-w-7xl mx-auto p-8">

        <h1 className="text-4xl font-bold mb-2">

          AI Interview Preparation

        </h1>

        <p className="text-slate-400 mb-8">

          Practice project-specific interview questions generated by AI.

        </p>

        {/* Cards */}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-10">

          <div className="bg-[#081222] border border-slate-700 rounded-xl p-6">

            <p className="text-slate-400">Project</p>

            <h2 className="text-2xl font-bold mt-3">

              {project?.name || "--"}

            </h2>

          </div>

          <div className="bg-[#081222] border border-slate-700 rounded-xl p-6">

            <p className="text-slate-400">Difficulty</p>

            <h2 className="text-2xl font-bold mt-3 text-yellow-400">

              {overallDifficulty}

            </h2>

          </div>

          <div className="bg-[#081222] border border-slate-700 rounded-xl p-6">

            <p className="text-slate-400">Questions</p>

            <h2 className="text-2xl font-bold mt-3">

              {questions.length}

            </h2>

          </div>

          <div className="bg-[#081222] border border-slate-700 rounded-xl p-6">

            <p className="text-slate-400">Progress</p>

            <h2 className="text-2xl font-bold mt-3 text-green-400">

              {completed.length}/{questions.length}

            </h2>

          </div>

        </div>

        {/* Search */}

        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search interview questions..."
          className="w-full bg-[#081222] border border-slate-700 rounded-xl px-5 py-4 outline-none mb-8"
        />

        {/* Questions */}

        <div className="space-y-6">

          {filteredQuestions.length === 0 ? (

            <div className="bg-[#081222] border border-slate-700 rounded-xl p-8 text-center text-slate-400">

              No interview questions found.

            </div>

          ) : (

            filteredQuestions.map((question, index) => (

              <div
                key={index}
                className="bg-[#081222] border border-slate-700 rounded-xl p-6"
              >

                <div className="flex justify-between items-center">

                  <h2 className="text-xl font-semibold">

                    Question {index + 1}

                  </h2>

                  <span
                    className={`px-3 py-1 rounded-full text-sm font-semibold ${
                      question.difficulty === "Easy"
                        ? "bg-green-600"
                        : question.difficulty === "Medium"
                        ? "bg-yellow-500 text-black"
                        : "bg-red-600"
                    }`}
                  >

                    {question.difficulty}

                  </span>

                </div>

                <p className="mt-5 text-slate-300 leading-7">

                  {question.question}

                </p>

                <button
                  onClick={() => toggleCompleted(index)}
                  className={`mt-6 px-5 py-2 rounded-lg ${
                    completed.includes(index)
                      ? "bg-green-600"
                      : "bg-slate-700 hover:bg-slate-600"
                  }`}
                >

                  {completed.includes(index)
                    ? "✓ Practiced"
                    : "Mark Practiced"}

                </button>

              </div>

            ))

          )}

        </div>

      </div>

    </div>

  );

};

export default IntQuestion;